name: PR Test and Merge

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install required packages
        run: |
          pip install pylint pytest

      - name: Lint text files
        run: |
          for file in *.txt; do
            if [ -s "$file" ]; then
              echo "$file is not empty"
            else
              echo "$file is empty"
              exit 1
            fi
          done

      - name: Run tests
        run: |
          pytest

  check-approval:
    if: success()
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check PR approval
        id: check_approval
        run: |
          APPROVALS=$(gh pr view ${{ github.event.pull_request.number }} --json reviews --jq '.reviews | map(select(.state == "APPROVED")) | length')
          echo "Number of approvals: $APPROVALS"
          if [ $APPROVALS -lt 2 ]; then  # Убедитесь, что количество одобрений соответствует вашим требованиям
            echo "Not enough approvals"
            exit 1
          fi

  merge:
    if: success()
    runs-on: ubuntu-latest
    needs: check-approval

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge pull request
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --merge
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
